### ISSUE TITLE
Cache status output

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-script#122]
Following https://code.launchpad.net/~ahasenack/ubuntu/+source/ubuntu-advantage-tools/+git/ubuntu-advantage-tools/+merge/337213/comments/884844, we want to remove "bash" and anything else that could cause delays from the login path. The best solution is to probably cache the output of the `ubuntu-advantage status` output, and maybe even update it out-of-band, so that the script run at login time at most prints existing text instead of running potentially costly code.

Brain storm:

a) Have the motd script itself manage the `ua status` cache.

- if the cache is too old, call the `ua status` command, use its output, and update the cache at the same time
- otherwise, use the cache value
Script might still "hickup" when updating the cache

b) have the motd script always use the cached value of `ua status`

- another process, like a cron job, updates that cache
- the motd script could check if the cache is too old and warn about it
- alternatively, or in addition to the above, the cache timestamp could be shown in the motd output

c) something entirely different: cache the whole output of the motd script

- the motd script would check for a cached output and print that, instead of reading a cached `ua status` output and parsing it
- another process, like the cron job, would run what is today the motd script and cache its output, i.e., those lines about the livepatch status, instead of caching just the output of `ua status`

**Comment by dpb1** [comment]
b) seems relevant since that is what happens with things like 90-updates-available.  Basically, just look for a cache, and print it if it exists.  I wouldn't bother with printing the freshness of the cache, I don't see that in any other of the script in the motd.

**Comment by panlinux** [comment]
The "(b)" option is basically replacing `ua_status=$(ua status)` in the motd script with `ua_status=$(cat /var/cache/ua-status.txt)`
The "(c)" option would be like replacing the entire motd script with this:
```
stamp=/var/cache/livepatch-motd.stamp
if [ -r "$stamp" ]; then
    cat "$stamp"
fi
```
In both cases, something has to update the stamp file of course. The only script that uses a timer is the news one. The rest try to be smart and check for important files in the system that were modified, like sources.list, time since reboot, etc. And they decide inline whether to print the cache or update-and-print the cache. The cache update is not done out of band.
Still have to figure out what's the best option here.

**Comment by panlinux** [comment]
Found `/var/snap/canonical-livepatch/common/last-check`, whose timestamp is used for the `last-check` field in the `canonical-livepatch status` output. We could use that to decide when it's time to update the cached output of `ua status`. On the other hand, it could be seen as an internal implementation detail (what if the path changes? Or the filename? Or how the snap decides to handle this?)
