### ISSUE TITLE
Non-interactive apt calls will halt on ucf prompts

### ISSUE THREAD

**Issue by basak** [CanonicalLtd/ubuntu-advantage-script#131]
13:51 <rbasak> ahasenack: in apt.sh, if you're using --force-confold you should probably also use the matching ucf flag

I think. I haven't checked but am making a note in case it bites later.

**Comment by basak** [comment]
See https://bugs.launchpad.net/cloud-images/+bug/1747464 for example

**Comment by powersj** [comment]
Closing this and we can re-open if confirmed with new client.
