### ISSUE TITLE
Configure the boot kernel if --allow-kernel-change was used

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-script#149]
If `--allow-kernel-change` is used with `enable-livepatch`, then a new kernel _might_ be installed by the tool. In this case, it will ask the user to boot into it.
Ideally, the tool itself should configure the system to boot into the kernel that was just installed, and perhaps even keep the machine on that kernel track. For example, if the running kernel is an `aws` one, and we install `linux-image-virtual`, then post-boot, if all went well, the `aws` kernel should be removed, so that normal updates will keep the machine with the `linux-image-virtual` kernel track.
It's not super clear how this can be achieved without complicating the code too much. We can use `grub-reboot` to have the next boot use any kernel we want, but that's temporary.

**Comment by powersj** [comment]
Not in scope for new master.
