### ISSUE TITLE
UA command should report support status

### ISSUE THREAD

**Issue by cjohnston1158** [CanonicalLtd/ubuntu-advantage-script#154]
Since we are trying to make the UA command a single command for anything to do with UA, it would be very helpful if the UA command would report on status similar (or the same way) that ubuntu-support-status does.

[Requested](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#heading=h.ukap75i6knb9) by Mark on 30 July

**Comment by powersj** [comment]
New master has this feature, closing this.
