### ISSUE TITLE
check for failure to install apt-transport-https

### ISSUE THREAD

**Issue by xnox** [CanonicalLtd/ubuntu-advantage-script#18]
If installting apt-transport-https fails, currently the script will abort.

Instead the error should be cought, and it should be non critical warning. something like this:

"Warning: Attempt to install apt-transprot-https failed, but is required to access ESM repository. Please investiage" - or something more friendly.

**Comment by albertodonato** [comment]
As mentioned, the `apt-get install` stderr is printed out on failure
