### ISSUE TITLE
sources.list file created for ESM is world-readable, leaks subscriber token to all local users

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-script#22]
Filed in launchpad as https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1700611

The sources.list.d entry for esm is created with the default umask, which means that all local users on the system have access to the token. Being able to read globally-readable files on the filesystem does not necessarily mean you are an ESM subscriber who should have access to this token and be able to access the ESM archive.

We should probably create this file mode 0600. (Though it is too late to fix this for precise.)

**Comment by albertodonato** [comment]
Reverted the change for this, since mode 600 breaks `apt policy` (and possibly other tools) as user

**Comment by dpb1** [comment]
given discussion in https://bugs.launchpad.net/ubuntu-advantage-script/+bug/1690270, I'm going to leave this closed.  If/when we desire a change in behavior, feel free to re-open.

**Comment by panlinux** [comment]
Let's reopen this.

Turns out we can use apt's auth.conf support: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811181

See man apt_auth.conf(5)
