### ISSUE TITLE
Document the lack of disable-fips

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-script#59]
For now, there is no way to disable FIPS support once it has been enabled. This should be documented in the manpage, and perhaps in the README file.

**Comment by dustinkirkland** [comment]
I would strongly advise there be a "disable-fips" action, which prints an
appropriate message to STDERR, and exits non-zero.

Dustin Kirkland
VP of Product
Canonical, Ltd.
@dustinkirkland

On Tue, Sep 12, 2017 at 12:23 PM, Andreas Hasenack <notifications@github.com
