### ISSUE TITLE
configure_fips() doesn't have a validation mechanism if bootdev isn't a UUID.

### ISSUE THREAD

**Issue by slashdd** [CanonicalLtd/ubuntu-advantage-script#79]
Current code:

```
configure_fips() {
    local bootdev fips_params result

    # if /boot has its own partition, then get the bootdevice
    # Note: /boot/efi  does not count
    bootdev=$(awk '!/^\s*#/ && $2 ~ /^\/boot\/?$/ { print $1 }' "$FSTAB")
    fips_params="fips=1"
    if [ -n "$bootdev" ]; then
        fips_params="$fips_params bootdev=$bootdev"
    fi
```

It look if a separate /boot partition exist in FSTAB, if nothing is return (nonzero value) it skip the bootdev portion but what if the $bootdev is nonzero and doesn't contain a UUID  ?

The first field of /boot line could be a device name in the form of (/dev/sda) or a label (LABEL=Boot).
I think iff UUID is needed, then we should add a validation mechanism.

```
# if /boot has its own partition, then get the bootdevice
    # Note: /boot/efi  does not count
    bootdev=$(awk '!/^\s*#/ && $2 ~ /^\/boot\/?$/ { print $1 }' "$FSTAB")
    fips_params="fips=1"
    if [[ -n "$bootdev" && "$bootdev" == "UUID"* ]]; then
        fips_params="$fips_params bootdev=$bootdev"
```

**Comment by albertodonato** [comment]
As discussed on IRC, device names, `LABEL` and `UUID` identifiers are all accepted as FIPS `bootdev`
