### ISSUE TITLE
fips-enable should fail when the AES instruction is not found

### ISSUE THREAD

**Issue by KellenRenshaw** [CanonicalLtd/ubuntu-advantage-script#82]
On machines without the AES instruction set (tested on libvirt/KVM VM) the FIPS kernel fails to boot with fips=1 on the kernel cmdline. Changing the CPU profile to include the AES instruction set (with no other changes) allows the kernel to boot.

The AES instruction's availability can be checked by "grep -m1 -o aes /proc/cpuinfo" outputting nothing if AES is not available and "aes" if it is.

The ubuntu-advantage-tools should detect if AES instruction set is present and if not output an error instead of installing, and then the host failing to boot.

**Comment by joylatten** [comment]
Actually, its probably AESNI availability that should be checked. The aes instructions are dependent on AESNI being available for amd64.

**Comment by albertodonato** [comment]
Does this check apply to any architecture that FIPS supports or just amd64?

**Comment by joylatten** [comment]
The check above only applies to amd64. It is probably a good idea to also check on ppc64el.  As discussed, for ppc64el we should probably check for "POWER8" in /proc/cpuinfo to verify vmx support.
